// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#include "NamespaceRedirect.h"

namespace RnWinRTTests
{
    [default_interface]
    runtimeclass MainPage : XAML_NAMESPACE.Controls.Page
    {
        MainPage();
    }
}
